# Variables
$mainMod = SUPER

# hyprsunset binds
bind = $mainMod, U, exec, pkill hyprsunset || hyprsunset
bind = $mainMod CONTROL SHIFT, down, exec, hyprctl hyprsunset temperature +500
bind = $mainMod CONTROL SHIFT, up  , exec, hyprctl hyprsunset temperature -500

# brightnessctl binds
bind = $mainMod CONTROL, down, global, caelestia:brightnessDown
bind = $mainMod CONTROL, up  , global, caelestia:brightnessUp

# Input
input {
    touchpad {
        tap-to-click = true
	    clickfinger_behavior = true
		scroll_factor = 1.2
    }
}

# Unbinds
unbind = $kbBrowser, exec, app2unit -- $browser
unbind = $kbEditor, exec, app2unit -- $editor
unbind = Super, G, exec, app2unit -- github-desktop
unbind = $kbFileExplorer, exec, app2unit -- $fileExplorer
unbind = Super+Alt, E, exec, app2unit -- nemo
unbind = Ctrl+Alt, Escape, exec, app2unit -- qps
unbind = Ctrl+Alt, V, exec, app2unit -- pavucontrol

# modified bindings related to special workspaces in "keybinds.conf", because of the hyprsunset binds


