#########################
#	      BINDINGS        #
#########################
$mainMod = SUPER

# hyprsunset binds
bind = $mainMod, U, exec, pkill hyprsunset || hyprsunset
bind = $mainMod CONTROL SHIFT, down, exec, hyprctl hyprsunset temperature +500
bind = $mainMod CONTROL SHIFT, up  , exec, hyprctl hyprsunset temperature -500

# brightnessctl binds
bind = $mainMod CONTROL, down, global, caelestia:brightnessDown
bind = $mainMod CONTROL, up  , global, caelestia:brightnessUp

########################
#	        INPUT        #
########################
input {
    touchpad {
        tap-to-click = true
	clickfinger_behavior = true
	scroll_factor = 1.2
    }
}

# modified bindings related to special workspaces in "keybinds.conf", because of the hyprsunset binds
# also modified apps binds in the same file, because I don't like them
